CREATE TABLE IF NOT EXISTS staff (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','manager','cashier','viewer') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  sku VARCHAR(40) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  cost DECIMAL(10,2) NOT NULL DEFAULT 0,
  qty INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  phone VARCHAR(40) NOT NULL DEFAULT '',
  email VARCHAR(190) NOT NULL DEFAULT '',
  points INT NOT NULL DEFAULT 0,
  visits INT NOT NULL DEFAULT 0,
  spend DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  receipt_no VARCHAR(20) NOT NULL UNIQUE,
  occurred_date DATE NOT NULL,
  occurred_time VARCHAR(5) NOT NULL,
  cashier_id INT NULL,
  cashier_name VARCHAR(120) NOT NULL,
  method ENUM('cash','card','mobile_money') NOT NULL,
  status ENUM('completed','refunded') NOT NULL DEFAULT 'completed',
  subtotal DECIMAL(10,2) NOT NULL,
  discount DECIMAL(10,2) NOT NULL DEFAULT 0,
  tax DECIMAL(10,2) NOT NULL DEFAULT 0,
  total DECIMAL(10,2) NOT NULL,
  paid DECIMAL(10,2) NOT NULL,
  change_due DECIMAL(10,2) NOT NULL DEFAULT 0,
  customer_id INT NULL,
  points_earned INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tx_cashier FOREIGN KEY (cashier_id) REFERENCES staff(id) ON DELETE SET NULL,
  CONSTRAINT fk_tx_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transaction_lines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  transaction_id INT NOT NULL,
  product_id INT NULL,
  name VARCHAR(160) NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  qty INT NOT NULL,
  is_manual TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_line_tx FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
  CONSTRAINT fk_line_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NULL,
  product_name VARCHAR(160) NOT NULL,
  delta INT NOT NULL,
  type ENUM('sale','purchase_return','adjustment') NOT NULL,
  reference VARCHAR(80) NOT NULL DEFAULT '',
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_log_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id TINYINT PRIMARY KEY DEFAULT 1,
  business_name VARCHAR(160) NOT NULL,
  business_type VARCHAR(80) NOT NULL,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  low_stock_threshold INT NOT NULL DEFAULT 6,
  points_per_unit DECIMAL(6,2) NOT NULL DEFAULT 1,
  receipt_footer VARCHAR(500) NOT NULL DEFAULT '',
  CONSTRAINT chk_settings_singleton CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS email_settings (
  id TINYINT PRIMARY KEY DEFAULT 1,
  from_name VARCHAR(120) NOT NULL,
  from_address VARCHAR(190) NOT NULL,
  reply_to VARCHAR(190) NOT NULL,
  host VARCHAR(190) NOT NULL DEFAULT '',
  port INT NOT NULL DEFAULT 587,
  username VARCHAR(190) NOT NULL DEFAULT '',
  password_secret VARCHAR(255) NOT NULL DEFAULT '',
  security ENUM('None','TLS','SSL') NOT NULL DEFAULT 'TLS',
  subject_template VARCHAR(255) NOT NULL,
  auto_send TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT chk_email_settings_singleton CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channels (
  id VARCHAR(40) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  kind ENUM('channel','direct') NOT NULL,
  member_count INT NOT NULL DEFAULT 1,
  unread INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  channel_id VARCHAR(40) NOT NULL,
  from_name VARCHAR(120) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_msg_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
